INSERT INTO user VALUES ('check@gmail.com', '$2a$15$Pkc55ZG0ZmUQNlkIAw7KGul36qdpVpyV95Eez1D.d0aFTEySRrvD6')

INSERT INTO ROLE VALUES(1,'admin')
INSERT INTO ROLE VALUES(2,'manager')
INSERT INTO ROLE VALUES(3,'editor')
INSERT INTO ROLE VALUES(4,'viewer')
